In [18]:
import numpy as np
import  pandas as pd
boolean=[True,False]
gender=["male","female"]
color=["white","black","yellow"]
data=pd.DataFrame({
    "height":np.random.randint(150,190,100),
    "weight":np.random.randint(40,90,100),
    "smoker":[boolean[x] for x in np.random.randint(0,2,100)],
    "gender":[gender[x] for x in np.random.randint(0,2,100)],
    "age":np.random.randint(15,90,100),
    "color":[color[x] for x in np.random.randint(0,len(color),100) ]
}
)
data

    height  weight  smoker  gender  age   color
0      187      85    True    male   17   white
1      186      88   False  female   31   black
2      170      82    True    male   55   white
3      178      72    True  female   34   white
4      158      65   False    male   24  yellow
..     ...     ...     ...     ...  ...     ...
95     168      40   False    male   36  yellow
96     189      83   False  female   71   white
97     167      49   False    male   17   white
98     161      73    True  female   28   black
99     172      69    True  female   70   black

[100 rows x 6 columns]

In [19]:
data["gender"] = data["gender"].map({"male":1, "female":0})
data.head(10)

   height  weight  smoker  gender  age   color
0     187      85    True       1   17   white
1     186      88   False       0   31   black
2     170      82    True       1   55   white
3     178      72    True       0   34   white
4     158      65   False       1   24  yellow
5     155      69   False       0   48  yellow
6     154      51   False       0   76  yellow
7     162      86   False       0   75   white
8     157      44   False       1   15   white
9     159      54    True       0   46   white